### ISSUE TITLE
Create some PHP related subreddits

### ISSUE THREAD

**Issue by vladyslavstartsev** [Fillll/reddit2telegram#136]
Hi!
Thanks for the project, it will be cool to add php related subreddits here.

This is what I mostly read
- https://www.reddit.com/r/PHP/
- https://www.reddit.com/r/laravel/
- https://www.reddit.com/r/symfony/ (white it has only 5k+ members it's relatively active)

Thanks again for the project!

**Comment by Fillll** [comment]
Done.
