### ISSUE TITLE
modularize posting

### ISSUE THREAD

**Issue by luckydonald** [Fillll/reddit2telegram#15]
All reddits share similar post types. So the code shouldn't be rewritten for each module.
The process of posing media from a reddit post should be in anoter utils file.

**Comment by luckydonald** [comment]
Would also make unit tests possible.

**Comment by Fillll** [comment]
You mean processing:

1. Video
2. Img
3. Gif
4. Link
5. Self Submision

?

**Comment by luckydonald** [comment]
Yeah, so then we could also make custom code per e.g. Hoster.

So 
E.g. Imgur gifs could be loaded directly as mp4. (Telegram would convert it to mp4 anyway)
Stuff like that.

**Comment by Fillll** [comment]
Looks like in https://github.com/Fillll/reddit2telegram/blob/master/utils.py#L16 I do the same. If you want to add any types, like video, I think it is correct place for it.

**Comment by luckydonald** [comment]
What is the tuple it returns?

**Comment by Fillll** [comment]
It returns:
( type_of_data_to_be_posted, data, file_extension_if_possible ).

So *data* can be just link, or list of links, or dict with link, and so on,

**Comment by Fillll** [comment]
I think it is solved.
