### ISSUE TITLE
Provide some info to run on server

### ISSUE THREAD

**Issue by tazihad** [Fillll/reddit2telegram#162]
Can you update the readme to give us some steps about how to run on own server?

**Comment by Fillll** [comment]
What info is necessary from your perspective?

**Comment by tazihad** [comment]
I know you have mentioned this a pet project. maybe I am asking too much. I am trying to setup a server in my own linux machine. But unable to figure out where to start. I got reddit and imgur api. But not sure how to start the server with custom subreddit. 
So, It would be helpful if you put some basic documentation about how to start the server.
