### ISSUE TITLE
Send Reddit Link Instead of Content for Text and Album Submission

### ISSUE THREAD

**Issue by CaringCat** [Fillll/reddit2telegram#196]
Sometimes I have saw some super-long text post, which is kind disrupting in the Telegram channel. Is there a way I set the bot to send title and link to that submission, but without the actual content get posted in the channel?

**Comment by Fillll** [comment]
Makes sense to me. In the backlog.

**Comment by Fillll** [comment]
Any ideas what should be considered as long text? 1000 chars? 4000 chars? 100 words?

**Comment by CaringCat** [comment]
or any kind of text and album submission?

**Comment by Fillll** [comment]
Solved already.

**Comment by CaringCat** [comment]
May I ask how is it been implemented? For example, I still saw long text post get submitted to the channel.

**Comment by Fillll** [comment]
Yeap, you can choose not to send self text of submission. And that's all, just link and title.

**Comment by CaringCat** [comment]
> Yeap, you can choose not to send self text of submission. 

Sorry, but I cannot find any mentions of it in [example config](https://github.com/Fillll/reddit2telegram/blob/master/reddit2telegram/channels/r_funny/app.py). Do you mean that if we change r2t.send_simple to, for example, "text=False", we can get link and title but not self text of submission?
