### ISSUE TITLE
Reduce the size of `cron_job.py` instance.

### ISSUE THREAD

**Issue by Fillll** [Fillll/reddit2telegram#221]
Now it's **~40MB**. Which consumes too much memory. Should be much less.

**Comment by lgyanf** [comment]
Creating a new Python process will still have a memory footprint measured in tens of megabytes. We can try to reduce that footprint by switching to forking (as in [`os.fork()`](https://docs.python.org/3/library/os.html#os.fork)) and rely on [COW](https://en.wikipedia.org/wiki/Copy-on-write) memory, but it would still be hard to control memory usage.

As an alternative, I can suggest switching to [`concurrent.futures`](https://docs.python.org/3/library/concurrent.futures.html) module with a `ProcessPoolExecutor` or a `ThreadPoolExecutor`, which will allow us to control how many tasks can be executed simultaneously.

Later we can also switch to async/await statements to reduce the footprint even more.

@Fillll would love to hear your feedback on this :)

**Comment by Fillll** [comment]
Sounds like [`concurrent.futures`](https://docs.python.org/3/library/concurrent.futures.html) could be a good solution, at least in short term, as we are losing some postings now.

Just to be on the same page. We want to fit **999MB** instance with all python processes and DB instances on the same machine.

Please go ahead and create PR. Thank you!

**Comment by Fillll** [comment]
Since merged, consider it done.
