### ISSUE TITLE
Project posts random text in channel

### ISSUE THREAD

**Issue by gibcheesepuffs** [Fillll/reddit2telegram#227]
I made the project run every 25 minutes or so, tracking posts from 3 subreddits and posting from both new and hot timelines. But after posting 2-3 posts it starts posts text in channel such as,

`13 → 0.13 > 0.06.`
`13 → 0.13 > 0.07.`

**Comment by Fillll** [comment]
Are you talking about your private installation? Has that been posted in the dev chat? Or to the target channel?

**Comment by gibcheesepuffs** [comment]
Yes, I did a private installation on a server. I also tried to send message in dev chat but my messages are getting deleted the next second.
