### ISSUE TITLE
No module named 'channels.unexpected'

### ISSUE THREAD

**Issue by faridcboy** [Fillll/reddit2telegram#36]
It took me a while to get this running without an error but even after I did, whenever I ran `docker-compose up reddit2tg` this message gets posted in the channel : 

`No module named 'channels.unexpected'`

However, the output doesnt show any errors:
```docker-compose up reddit2tg
Recreating reddit2telegram_reddit2tg_1 ...
Recreating reddit2telegram_reddit2tg_1 ... done
Attaching to reddit2telegram_reddit2tg_1
reddit2tg_1  | Sentry is attempting to send 1 pending error messages
reddit2tg_1  | Waiting up to 10 seconds
reddit2tg_1  | Press Ctrl-C to quit
reddit2telegram_reddit2tg_1 exited with code 0

**Comment by faridcboy** [comment]
@Fillll @yyakko I totally understand that its not your duty but it would have been great if you had any tips or points that could have helped!

**Comment by Fillll** [comment]
Still the same?
