### ISSUE TITLE
Private subreddits

### ISSUE THREAD

**Issue by mshafiei** [Fillll/reddit2telegram#58]
Hi,

Thanks for the valuable code. Does it also work for private subreddits? What about with private Telegram channels or groups?

**Comment by Fillll** [comment]
I think it is possible to make it work with private subreddits, If give to the boy right permissions.

But we try to keep this not only for public channels.

**Comment by Fillll** [comment]
48208c74a81224ab7bb4a00a13d158a490adb96c
