### ISSUE TITLE
Bot freezes multiple times per day

### ISSUE THREAD

**Issue by aBARICHELLO** [Fillll/reddit2telegram#85]
In multiple days the bot just stops sending messages after some time, no particular hour seems to be causing the problem.
To see an example check the post history of [this channel](https://t.me/r_wholesomememes) where the bot is supposed to post once every two hours.
Happy to provide any info that can help.

**Comment by Fillll** [comment]
Let's check. It should be better now.
Isn't it?

**Comment by aBARICHELLO** [comment]
Yes, last time it happened was at October 25. I will notify you if it happens again, thanks.

Abraços,
Barichello

________________________________

**Comment by aBARICHELLO** [comment]
Yes, last time it happened was at October 25, if it happens again I'll notify you. Thanks
