### ISSUE TITLE
Use python-telegram-bot instead of Telepot

### ISSUE THREAD

**Issue by RememberTheAir** [Fillll/reddit2telegram#98]
Telepot [is no longer mantained](https://github.com/nickoala/telepot/issues/408#issuecomment-409827643) and lacks most of the features the bot API introduced during the past 2 years (namely: the ability to send albums). It would be a good idea to move to [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot), which seems to be the most up-to-date, robust and popular python bot API library

**Comment by crapStone** [comment]
Are you currently working on this?

**Comment by crapStone** [comment]
opened PR: #117

**Comment by Fillll** [comment]
Done in 6e0e092539499cebdda8f8cb0cac52b95c9b1daa.
